---

- name: add GPG signing key for Influxdb repository
  apt_key: 
    state: present
    url: https://repos.influxdata.com/influxdb.key 

- name: install Influxdb repository
  apt_repository: 
    state: present
    filename: influxdb
    repo: 'deb https://repos.influxdata.com/ubuntu focal stable'
  register: influxdbrepo
  
- name: update apt repository
  apt:
    update_cache: yes
  when: influxdbrepo.changed

- name: Install Influxdb packages
  package: 
    state: latest
    name: influxdb
  register: influxdbpkg

- name: Generate configuration files
  template:
    owner: root
    group: root
    mode: 0644
    dest: /etc/influxdb/influxdb.conf
    src: influxdb.conf
  register: influxconf

- name: Configure cluster default file if necessary
  template:
    owner: root
    group: root
    mode: 0644
    dest: /etc/default/influxdb
    src: influxdefault
  when: influxdb_master_ip is defined
  register: influxclusterconfig

- name: start Influxdb
  service: 
    state: restarted
    name: influxdb 
    enabled: yes
  when: influxdbpkg.changed or influxconf.changed or influxclusterconfig.changed