---

- name: add GPG signing key for Influxdb repository
  apt_key: 
    state: present
    url: https://repos.influxdata.com/influxdb.key 

- name: install Influxdb repository
  apt_repository: 
    state: present
    filename: influxdb
    repo: 'deb https://repos.influxdata.com/ubuntu focal stable'
  register: influxdbrepo
  
- name: update apt repository
  apt:
    update_cache: yes
  when: influxdbrepo.changed

- name: Install Influxdb packages
  package: 
    state: latest
    name: influxdb
  register: influxdbpkg   

- name: start Influxdb
  service: 
    state: restarted
    name: influxdb 
    enabled: yes
  when: influxdbpkg.changed