---

- name: add key for mongo repository
  apt_key:
    state: present
    url: "https://www.mongodb.org/static/pgp/server-4.4.asc"
  register: mongokey

- name: install mongo repository
  apt_repository:
    state: present
    filename: mongodb
    repo: 'deb [ arch={{ mongo_arch }} ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ mongo_version }} multiverse'
  register: mongorepo

- name: update apt repository
  apt:
    update_cache: yes
  when: mongorepo.changed

- name: install mongodb
  package:
    state: latest
    name: mongodb-org
  register: mongopkg

- name: set sysctl limits for mongo
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: nofile, type: soft, value: 294180, domain: "*"}
    - {name: nofile, type: hard, value: 294180, domain: "*"}
    - {name: nproc, type: hard, value: 294180, domain: "*"}
    - {name: nproc, type: soft, value: 294180, domain: "*"}

- name: configure mongo to listen on all ports
  template:
    dest: /etc/mongo.conf
    owner: root
    group: root
    mode: 0644
    src: mongo.conf
  register: mongotemplate

- name: start mongo
  service:
    name: mongod
    state: restarted
    enabled: yes
  when: mongopkg.changed or mongotemplate.changed

- name: wait for mongo to boot
  wait_for:
    port: "{{ mongo_port }}"
    host: "{{ mongo_host }}"
    delay: 10

- name: initialize mongo replicasets
  command: mongo --eval '"rs.initiate()"'
  when: mongopkg.changed and mongo_cluster_host is defined

- name: add replication nodes
  command: mongo --eval 'rs.add("{{item}}")'
  with_items:
    - "{{ mongodb_nodes }}"
  when: mongodb_nodes is defined and mongo_cluster_host is defined
